### ISSUE TITLE
Deploying Azure Delta Lake does not work

### ISSUE THREAD

**Issue by iBoonz** [microsoft/healthcare-apis-samples#50]
When trying to deploy via the Azure Button, I get the error below

![image](https://user-images.githubusercontent.com/2930374/204759711-fed14313-fe9f-4a67-af9a-0437db3a7926.png)

When I upload the manual deployment script, I get an error with the Databricks deployment
![image](https://user-images.githubusercontent.com/2930374/204763032-56e693e0-569c-4065-a87b-b48cf0f9f673.png)

**Deployment script output file located in: '/mnt/azscripts/azscriptoutput/scriptoutputs.json' has an invalid syntax.**

`{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentScriptInvalidOutputs\",\r\n        \"message\": \"Deployment script output file located in: '/mnt/azscripts/azscriptoutput/scriptoutputs.json' has an invalid syntax. Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information.\"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}`

**Comment by darnharris** [comment]
Merged faulty fhir reference "52".
